CREATE TABLE IF NOT EXISTS partners (
  id INT AUTO_INCREMENT PRIMARY KEY,
  subdomain VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  logo_url VARCHAR(500) DEFAULT NULL,
  primary_color VARCHAR(20) NOT NULL DEFAULT '#E61E4D',
  email VARCHAR(255) NOT NULL,
  markup_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  smtp_host VARCHAR(255) DEFAULT NULL,
  smtp_port SMALLINT UNSIGNED DEFAULT NULL,
  smtp_user VARCHAR(255) DEFAULT NULL,
  smtp_pass VARCHAR(255) DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_subdomain (subdomain),
  INDEX idx_active (active)
);
