CREATE TABLE IF NOT EXISTS cleaning_fees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  property_id VARCHAR(100) DEFAULT NULL UNIQUE COMMENT 'NULL means default for all properties',
  per_person_per_night DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
